apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml  
  - argocd-install-v2.3.3.yaml
  - projects.yaml
  - ../argocd-applications/node-express-mysql.yaml
  - ../argocd-applications/node-express-mysql.yaml
  - ../argocd-applications/node-express-mysql.yaml


configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - "timeout.reconciliation=15s"

patchesStrategicMerge:
  - patch-argocd-server-loadbalancer.yaml
