apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  # annotations:
  #     notifications.argoproj.io/subscribe.slack: channel-name
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ingress-nginx
    repoURL: https://github.com/adamroddick/argocd-applications.git
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
