---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: letsencrypt@adamcybersec.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
          - "adamcybersec.com"
      dns01:
        cloudflare:
          email: letsencrypt@adamcybersec.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token